apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secrets-deep-log
  namespace: deep-log
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: deep-log-backend
    kind: SecretStore
  target:
    name: deep-log-secrets
  dataFrom:
    - extract:
        key: k8s-secrets/deep-log
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: deep-log-backend
  namespace: deep-log
spec:
  provider:
    vault:
      server: "https://vault-lasdpc.icmc.usp.br"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "role-deep-log"
          serviceAccountRef:
            name: deep-log