app_name      = "terraform-lasdpc-states"
app_gatling   = "lasdpc-gatling-results"
app_locust    = "lasdpc-locust-results"
env           = "prod"
resource_name = "application-metrics"
region        = "us-east-1"
