kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: sock-shop
  name: account-sock-shop-manager-ispal

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: sock-shop
  name: role-sock-shop-manager-ispal
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["chaos-mesh.org"]
  resources: [ "*" ]
  verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-sock-shop-manager-ispal
  namespace: sock-shop
subjects:
- kind: ServiceAccount
  name: account-sock-shop-manager-ispal
  namespace: sock-shop
roleRef:
  kind: Role
  name: role-sock-shop-manager-ispal
  apiGroup: rbac.authorization.k8s.io

