apiVersion: v1
kind: Namespace
metadata:
  name: deep-log
---
apiVersion: batch/v1
kind: Job
metadata:
  name: deeplog-prom-exporter
  namespace: deep-log
  labels:
    job-name: deeplog-prom-exporter
spec:
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
      - name: deeplog-prom-exporter
        image: diegopedroso/deeplog-prom-exporter:CIRCLE_TAG_REPLACE
        envFrom:
        - secretRef:
            name: deep-log-secrets
      restartPolicy: Never
