apiVersion: v1
kind: Namespace
metadata:
  name: deep-log
---
apiVersion: batch/v1
kind: Job
metadata:
  name: loki-get-metrics
  namespace: deep-log
  labels:
    job-name: loki-get-metrics
spec:
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
      - name: loki-get-metrics
        image: diegopedroso/deep-log:v8
        command: ["python", "loki.py", "--log-level", "debug"]
        envFrom:
        - secretRef:
            name: deep-log-secrets      
      restartPolicy: Never
---  
apiVersion: batch/v1
kind: Job
metadata:
  name: deep-log-training
  namespace: deep-log
  labels:
    job-name: loki-get-metrics
spec:
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
      - name: deep-log-training
        image: diegopedroso/deep-log:v8
        command: ["python", "deep_log.py", "--log-level", "debug"]
        envFrom:
        - secretRef:
            name: deep-log-secrets
      restartPolicy: Never