apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: carts-db-onefail
  namespace: sock-shop
spec:
  action: pod-failure
  mode: one
  duration: '5m'
  selector:
    labelSelectors:
      name: 'carts-db'
