apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: shipping-bandwidth
  namespace: sock-shop
spec:
  action: bandwidth
  mode: all
  bandwidth:
    rate: '200kbps'
    limit: 20971520
    buffer: 10000
  duration: '10m'
  selector:
    labelSelectors:
      name: 'shipping'
