apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: shipping-delay
  namespace: sock-shop
spec:
  action: delay
  mode: all
  delay:
    latency: '200ms'
    correlation: '75'
    jitter: '15ms'
  duration: '10m'
  selector:
    labelSelectors:
      name: 'shipping'
