apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: shipping-mem
  namespace: sock-shop
spec:
  stressors:
    memory:
      workers: 4
      size: '512MB'
  mode: all
  duration: '10m'
  selector:
    labelSelectors:
      name: 'shipping'

