apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: user-failure
  namespace: sock-shop
spec:
  action: pod-failure
  mode: all
  duration: '5m'
  selector:
    labelSelectors:
      name: 'user'
