env                 = "prod"
region              = "us-east-1"
key_pair            = "prod"
resource_name       = "application-metrics"
username            = ["Sarita_Bruschi", "Julio_Estrella", "Lucas_Pulcinelli", "Giovanni_Shibaki", "Pedro_Grando", "Henrique_Lecco", "Luciana_Marques"] # for all users
username_read_only  = ["Lucas_Pulcinelli", "Giovanni_Shibaki", "Pedro_Grando"]
username_dev        = ["Sarita_Bruschi", "Julio_Estrella", "Henrique_Lecco", "Diego_Frazatto_Pedroso"]
username_admins     = ["Diego_Frazatto_Pedroso"]
username_billing    = ["Luciana_Marques"]