---
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: spot
  annotations:
    kubernetes.io/description: "NodePool for provisioning spot capacity"
spec:
  template:
    spec:
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["c", "r", "t"]
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        name: karpenter-spot
  limits:
    cpu: 15
    memory: 20Gi
---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: karpenter-spot
  annotations:
    kubernetes.io/description: "General purpose EC2NodeClass for running Amazon Linux 2 nodes"
spec:
  amiFamily: AL2 # Amazon Linux 2
  role: "lasdpc-icmc-spot-eks-node-group-20240514211505414700000001"
  subnetSelectorTerms:
    - tags:
        team: "icmc"
  securityGroupSelectorTerms:
    - tags:
        Env: "prod"
  tags:
    managed-by: karpenter
    Name: karpenter-lasdpc-icmc-spot