loki:
  auth_enabled: false
  commonConfig:
    path_prefix: /var/loki
    replication_factor: 1
  compactor:
    apply_retention_interval: 1h
    compaction_interval: 5m
    retention_delete_worker_count: 500
    retention_enabled: true
    shared_store: s3
    working_directory: /data/compactor
  limits_config:
    retention_period: 365d
    max_entries_limit_per_query: 5000000

  config:
      schema_config:
        configs:
        - from: 2020-05-15
          store: boltdb-shipper
          object_store: s3
          schema: v11
          index:
            period: 24h
            prefix: loki_index_
        
      storage_config:
        aws:
          region: us-east-1
          bucketnames: lasdpc-loki-logs
          secret_access_key: ${secret_access_key}
          access_key_id: ${access_key_id}
          s3forcepathstyle: false
        boltdb_shipper:
          shared_store: s3
          cache_ttl: 24h
  write:
     replicas: 2
  read:
    replicas: 1