apiVersion: v1
kind: Namespace
metadata:
  name: hello-app1
---
apiVersion: v1
kind: Service
metadata:
  name: hello-app1
  namespace: hello-app1
  labels:
    app: hello-app1
spec:
  selector:
    app: hello-app1
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app1
  namespace: hello-app1
  labels:
    app: hello-app1
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: hello-app1
  template:
    metadata:
      labels:
        app: hello-app1
    spec:
      containers:
      - name: hello-app1
        image: diegopedroso/hello-app1:CIRCLE_TAG_REPLACE
        ports:
        - containerPort: 8080