apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dev
spec:
  acme:
    email: diegopedroso@usp.br
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: secret-tls-key
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx