apiVersion: v1
kind: ServiceAccount
metadata:
  name: locust-distributor-serviceaccount
  namespace: monitoring
---
apiVersion: batch/v1
kind: Job
metadata:
  name: locust-metrics-distributor
  namespace: monitoring
  labels:
    job-name: locust-metrics-distributor
spec:
  completions: 1
  parallelism: 1
  template:
    spec:
      serviceAccountName: locust-distributor-serviceaccount
      containers:
      - name: locust-metrics-distributor
        image: diegopedroso/locust-metrics-distributor:20250103.04
        envFrom:
        - secretRef:
            name: locust-distributor-secrets
      restartPolicy: Never
