apiVersion: v1
kind: Namespace
metadata:
  name: nodegraph-generator
---
apiVersion: v1
kind: Service
metadata:
  name: nodegraph-generator
  namespace: nodegraph-generator
  labels:
    app: nodegraph-generator
spec:
  selector:
    app: nodegraph-generator
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodegraph-generator
  namespace: nodegraph-generator
  labels:
    app: nodegraph-generator
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: nodegraph-generator
  template:
    metadata:
      labels:
        app: nodegraph-generator
    spec:
      containers:
      - name: nodegraph-generator
        image: diegopedroso/nodegraph-generator:CIRCLE_TAG_REPLACE
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_URL
          value: redis-service.nodegraph-generator.svc.cluster.local
        - name: PROMETHEUS_URL
          value: "http://kube-prometheus-kube-prome-prometheus.monitoring:9090"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: nodegraph-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: nodegraph-generator
spec:
  selector:
    app: redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
  type: ClusterIP