apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: Service
metadata:
  name: nodegraph-generator
  namespace: monitoring
  labels:
    app: nodegraph-generator
spec:
  selector:
    app: nodegraph-generator
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodegraph-generator
  namespace: monitoring
  labels:
    app: nodegraph-generator
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: nodegraph-generator
  template:
    metadata:
      labels:
        app: nodegraph-generator
    spec:
      containers:
      - name: nodegraph-generator
        image: diegopedroso/nodegraph-generator:CIRCLE_TAG_REPLACE
        ports:
        - containerPort: 8080
        env:
        - name: PROMETHEUS_URL
          value: "http://prometheus.istio-system:9090"
