apiVersion: v1
kind: Namespace
metadata:
  name: go-multithread
---
apiVersion: v1
kind: Service
metadata:
  name: go-multithread
  namespace: go-multithread
  labels:
    app: go-multithread
spec:
  selector:
    app: go-multithread
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-multithread
  namespace: go-multithread
  labels:
    app: go-multithread
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-multithread
  template:
    metadata:
      labels:
        app: go-multithread
    spec:
      containers:
      - name: go-multithread
        image: diegopedroso/go-multithread:CIRCLE_TAG_REPLACE
        ports:
        - containerPort: 8080
