apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: diego.pedroso@usp.br
    privateKeySecretRef:
      name: letsencrypt-production
    http01:  
    solvers:
      - http01:
          ingress:
            class: nginx
