---
apiVersion: v1
kind: Namespace
metadata:
  name: simedape-synthetic
---  
apiVersion: v1
kind: Service
metadata:
  name: synthetic-sao-paulo
  namespace: simedape-synthetic
  labels:
    app: synthetic-sao-paulo
    service: synthetic-sao-paulo
spec:
  ports:
  - protocol: TCP
    port: 22
    name: ssh
  selector:
    app: synthetic-sao-paulo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: synthetic-sao-paulo
  namespace: simedape-synthetic
  labels:
    app: synthetic-sao-paulo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synthetic-sao-paulo
  template:
    metadata:
      labels:
        app: synthetic-sao-paulo
    spec:
      containers:
      - name: synthetic-sao-paulo
        image: docker.io/uxhabam/sao_paulo_synthetic:latest
        ports:
        - protocol: TCP
          name: ssh
          containerPort: 22
        imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux