- hosts: master
  become: yes
  gather_facts: false
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"


- hosts: workers
  become: yes
  tasks:

    - name: deploy kubelet file on docker env
      shell: |
        cat << EOF > /etc/docker/daemon.json
          {
            "exec-opts": ["native.cgroupdriver=systemd"]
          }
        EOF

    - name: restart docker
      shell: systemctl restart docker

    - name: join cluster
      shell: "{{ hostvars['master'].join_command }} >> node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt
