---
apiVersion: v1
kind: Namespace
metadata:
  name: baynet
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: baynet-deployment
  namespace: baynet
spec:
  replicas: 3
  selector:
    matchLabels:
      app: baynet
  template:
    metadata:
      labels:
        app: baynet
    spec:
      containers:
      - name: baynet-container
        image: diegopedroso/baynet:CIRCLE_TAG_REPLACE
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: baynet-service
  namespace: baynet
spec:
  selector:
    app: baynet
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: baynet-ingress
  namespace: baynet
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: maia-lasdpc.icmc.usp.br
    http:
      paths:
      - path: /baynet
        pathType: Prefix
        backend:
          service:
            name: baynet-service
            port:
              number: 80
  tls:
  - hosts:
    - maia-lasdpc.icmc.usp.br
    secretName: baynet-tls-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: baynet-cert-prod
  namespace: baynet
spec:
  dnsNames:
  - maia-lasdpc.icmc.usp.br
  duration: 8640h0m0s
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  renewBefore: 7440h0m0s
  secretName: baynet-tls-secret