on:
  push:
    branches: [main]

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get commit history
        id: get_commits
        run: |
          git log --pretty=format:'%s' > commits.txt  # Get all commit messages

      - name: Generate changelog
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const commits = fs.readFileSync('commits.txt', 'utf8').split('\n');
            let changelog = '';

            // Append each commit to the changelog, formatted properly
            commits.forEach(commit => {
              const match = commit.match(/^(feat|fix)\((.*)\): (.*)/);
              if (match) {
                const type = match[1];
                const branch = match[2];
                const description = match[3];
                changelog += `* **${type}(${branch})**: ${description}\n`;
              }
            });

            // Read current changelog file if it exists, and append new content
            if (fs.existsSync('CHANGELOG.md')) {
              const existingChangelog = fs.readFileSync('CHANGELOG.md', 'utf8');
              changelog = existingChangelog + '\n' + changelog;
            }

            // Write the updated changelog to the file
            fs.writeFileSync('CHANGELOG.md', changelog);

      - name: Commit and push changelog
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md"
          git push origin main

      - name: Get the latest release tag
        id: get_latest_release
        run: |
          latest_tag=$(git tag -l "v*" | sort -V | tail -n 1)
          if [ -z "$latest_tag" ]; then
            latest_tag="v1.0.0"  # Default if no tags exist
          fi
          echo "Latest tag is $latest_tag"
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV

      - name: Create new release tag
        id: create_release
        run: |
          # Get the latest tag and increment the version
          VERSION_TAG=${{ env.latest_tag }}
          if [ -z "$VERSION_TAG" ]; then
            VERSION_TAG="v1.0.0"
          else
            # Increment the version number (last part of the tag)
            NEW_VERSION=$(echo $VERSION_TAG | awk -F. -v OFS=. '{$NF++;print}')
            VERSION_TAG="v$NEW_VERSION"
          fi

          # Check if the tag already exists
          TAG_EXISTS=$(git tag -l | grep -w "$VERSION_TAG")
          if [ -n "$TAG_EXISTS" ]; then
            echo "Tag $VERSION_TAG already exists, skipping release creation."
            exit 0
          fi

          # Create a release with the new version tag
          COMMIT_MESSAGE=$(tail -n 1 commits.txt)
          gh release create "$VERSION_TAG" --title "$VERSION_TAG" --notes "$COMMIT_MESSAGE" --generate-notes

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
