name: Create Release

on:
  push:
    branches: [main]
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Changelog
        uses: Bullrich/generate-release-changelog@master
        id: Changelog
        env:
          REPO: ${{ github.repository }}
      - name: Determine Version
        id: determine_version
        run: |
          # Extract major, minor, and patch from tag (e.g., v0.1.2)
          tag="${GITHUB_REF#refs/tags/}"
          IFS='.' read -r major minor patch <<< "$tag"
          # Increment patch version
          ((patch++))
          # Construct new version string
          new_version="v${major}.${minor}.${patch}"
          echo "::set-output name=new_version::$new_version"
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.determine_version.outputs.new_version }}
          release_name: "Release ${{ steps.determine_version.outputs.new_version }}"
          body: |
            ${{ steps.Changelog.outputs.changelog }}
          draft: false
          prerelease: false