name: Generate Changelog and Create Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Generate Changelog and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Generate changelog and release
        run: npx semantic-release

      - name: Push changes (if any)
        run: git push --follow-tags origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
