name: Changelog Tracking

on:
  push:
    branches: [main]

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Changelog
        uses: Bullrich/generate-release-changelog@master
        id: Changelog
        env:
          REPO: ${{ github.repository }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v-${{github.run_number}}"
          release_name: "release-${{github.run_number}}"
          body: |
            ${{ steps.Changelog.outputs.changelog }}
          draft: false
          prerelease: false
