name: Generate Changelog and Create Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Generate Changelog and Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Changelog CI
        uses: saadmk11/changelog-ci@v1.1.2
