name: Generate Changelog and Create Release

on:
  push:
    branches: [main]

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get commit history
        id: get_commits
        run: |
          git log --pretty=format:'%s' -n 100 > commits.txt

      - name: Generate changelog
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const commits = fs.readFileSync('commits.txt', 'utf8').split('\n');
            let changelog = '';

            commits.forEach(commit => {
              const match = commit.match(/^(feat|fix)\((.*)\): (.*)/); 
              if (match) {
                const type = match[1];
                const branch = match[2];
                const description = match[3];
                changelog += `* **${type}(${branch})**: ${description}\n`;
              }
            });

            fs.writeFileSync('CHANGELOG.md', changelog);

      - name: Commit and push changelog
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md"
          git push origin main

  create-release:
    runs-on: ubuntu-latest
    needs: generate-changelog
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.sha }}
          release_name: ${{ github.sha }}
          body: ${{ steps.generate-changelog.outputs.changelog }}
          draft: false
          prerelease: false